// Eurovision 2025 Participating Countries
const countries2025 = [
    { name: "Albania", code: "AL", flag: "🇦🇱", broadcaster: "RTSH", isBigFive: false, isHost: false },
    { name: "Armenia", code: "AM", flag: "🇦🇲", broadcaster: "AMPTV", isBigFive: false, isHost: false },
    { name: "Australia", code: "AU", flag: "🇦🇺", broadcaster: "SBS", isBigFive: false, isHost: false },
    { name: "Austria", code: "AT", flag: "🇦🇹", broadcaster: "ORF", isBigFive: false, isHost: false },
    { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", broadcaster: "İTV", isBigFive: false, isHost: false },
    { name: "Belgium", code: "BE", flag: "🇧🇪", broadcaster: "RTBF/VRT", isBigFive: false, isHost: false },
    { name: "Croatia", code: "HR", flag: "🇭🇷", broadcaster: "HRT", isBigFive: false, isHost: false },
    { name: "Cyprus", code: "CY", flag: "🇨🇾", broadcaster: "CyBC", isBigFive: false, isHost: false },
    { name: "Czech Republic", code: "CZ", flag: "🇨🇿", broadcaster: "ČT", isBigFive: false, isHost: false },
    { name: "Denmark", code: "DK", flag: "🇩🇰", broadcaster: "DR", isBigFive: false, isHost: false },
    { name: "Estonia", code: "EE", flag: "🇪🇪", broadcaster: "ERR", isBigFive: false, isHost: false },
    { name: "Finland", code: "FI", flag: "🇫🇮", broadcaster: "Yle", isBigFive: false, isHost: false },
    { name: "France", code: "FR", flag: "🇫🇷", broadcaster: "France Télévisions", isBigFive: true, isHost: false },
    { name: "Georgia", code: "GE", flag: "🇬🇪", broadcaster: "GPB", isBigFive: false, isHost: false },
    { name: "Germany", code: "DE", flag: "🇩🇪", broadcaster: "ARD/NDR", isBigFive: true, isHost: false },
    { name: "Greece", code: "GR", flag: "🇬🇷", broadcaster: "ERT", isBigFive: false, isHost: false },
    { name: "Iceland", code: "IS", flag: "🇮🇸", broadcaster: "RÚV", isBigFive: false, isHost: false },
    { name: "Ireland", code: "IE", flag: "🇮🇪", broadcaster: "RTÉ", isBigFive: false, isHost: false },
    { name: "Israel", code: "IL", flag: "🇮🇱", broadcaster: "IPBC", isBigFive: false, isHost: false },
    { name: "Italy", code: "IT", flag: "🇮🇹", broadcaster: "RAI", isBigFive: true, isHost: false },
    { name: "Latvia", code: "LV", flag: "🇱🇻", broadcaster: "LTV", isBigFive: false, isHost: false },
    { name: "Lithuania", code: "LT", flag: "🇱🇹", broadcaster: "LRT", isBigFive: false, isHost: false },
    { name: "Luxembourg", code: "LU", flag: "🇱🇺", broadcaster: "RTL", isBigFive: false, isHost: false },
    { name: "Malta", code: "MT", flag: "🇲🇹", broadcaster: "PBS", isBigFive: false, isHost: false },
    { name: "Montenegro", code: "ME", flag: "🇲🇪", broadcaster: "RTCG", isBigFive: false, isHost: false },
    { name: "Netherlands", code: "NL", flag: "🇳🇱", broadcaster: "AVROTROS", isBigFive: false, isHost: false },
    { name: "Norway", code: "NO", flag: "🇳🇴", broadcaster: "NRK", isBigFive: false, isHost: false },
    { name: "Poland", code: "PL", flag: "🇵🇱", broadcaster: "TVP", isBigFive: false, isHost: false },
    { name: "Portugal", code: "PT", flag: "🇵🇹", broadcaster: "RTP", isBigFive: false, isHost: false },
    { name: "San Marino", code: "SM", flag: "🇸🇲", broadcaster: "SMRTV", isBigFive: false, isHost: false },
    { name: "Serbia", code: "RS", flag: "🇷🇸", broadcaster: "RTS", isBigFive: false, isHost: false },
    { name: "Slovenia", code: "SI", flag: "🇸🇮", broadcaster: "RTVSLO", isBigFive: false, isHost: false },
    { name: "Spain", code: "ES", flag: "🇪🇸", broadcaster: "RTVE", isBigFive: true, isHost: false },
    { name: "Sweden", code: "SE", flag: "🇸🇪", broadcaster: "SVT", isBigFive: false, isHost: false },
    { name: "Switzerland", code: "CH", flag: "🇨🇭", broadcaster: "SRG SSR", isBigFive: false, isHost: true },
    { name: "Ukraine", code: "UA", flag: "🇺🇦", broadcaster: "UA:PBC", isBigFive: false, isHost: false },
    { name: "United Kingdom", code: "GB", flag: "🇬🇧", broadcaster: "BBC", isBigFive: true, isHost: false }
];

// Eurovision 2026 Participating Countries
const countries2026 = [
    { name: "Albania", code: "AL", flag: "🇦🇱", broadcaster: "RTSH", isBigFive: false, isHost: false },
    { name: "Armenia", code: "AM", flag: "🇦🇲", broadcaster: "AMPTV", isBigFive: false, isHost: false },
    { name: "Australia", code: "AU", flag: "🇦🇺", broadcaster: "SBS", isBigFive: false, isHost: false },
    { name: "Austria", code: "AT", flag: "🇦🇹", broadcaster: "ORF", isBigFive: false, isHost: true },
    { name: "Azerbaijan", code: "AZ", flag: "🇦🇿", broadcaster: "İTV", isBigFive: false, isHost: false },
    { name: "Belgium", code: "BE", flag: "🇧🇪", broadcaster: "RTBF/VRT", isBigFive: false, isHost: false },
    { name: "Bulgaria", code: "BG", flag: "🇧🇬", broadcaster: "BNT", isBigFive: false, isHost: false },
    { name: "Croatia", code: "HR", flag: "🇭🇷", broadcaster: "HRT", isBigFive: false, isHost: false },
    { name: "Cyprus", code: "CY", flag: "🇨🇾", broadcaster: "CyBC", isBigFive: false, isHost: false },
    { name: "Czech Republic", code: "CZ", flag: "🇨🇿", broadcaster: "ČT", isBigFive: false, isHost: false },
    { name: "Denmark", code: "DK", flag: "🇩🇰", broadcaster: "DR", isBigFive: false, isHost: false },
    { name: "Estonia", code: "EE", flag: "🇪🇪", broadcaster: "ERR", isBigFive: false, isHost: false },
    { name: "Finland", code: "FI", flag: "🇫🇮", broadcaster: "Yle", isBigFive: false, isHost: false },
    { name: "France", code: "FR", flag: "🇫🇷", broadcaster: "France Télévisions", isBigFive: true, isHost: false },
    { name: "Georgia", code: "GE", flag: "🇬🇪", broadcaster: "GPB", isBigFive: false, isHost: false },
    { name: "Germany", code: "DE", flag: "🇩🇪", broadcaster: "ARD/NDR", isBigFive: true, isHost: false },
    { name: "Greece", code: "GR", flag: "🇬🇷", broadcaster: "ERT", isBigFive: false, isHost: false },
    { name: "Israel", code: "IL", flag: "🇮🇱", broadcaster: "IPBC", isBigFive: false, isHost: false },
    { name: "Italy", code: "IT", flag: "🇮🇹", broadcaster: "RAI", isBigFive: true, isHost: false },
    { name: "Latvia", code: "LV", flag: "🇱🇻", broadcaster: "LTV", isBigFive: false, isHost: false },
    { name: "Lithuania", code: "LT", flag: "🇱🇹", broadcaster: "LRT", isBigFive: false, isHost: false },
    { name: "Luxembourg", code: "LU", flag: "🇱🇺", broadcaster: "RTL", isBigFive: false, isHost: false },
    { name: "Malta", code: "MT", flag: "🇲🇹", broadcaster: "PBS", isBigFive: false, isHost: false },
    { name: "Moldova", code: "MD", flag: "🇲🇩", broadcaster: "TRM", isBigFive: false, isHost: false },
    { name: "Montenegro", code: "ME", flag: "🇲🇪", broadcaster: "RTCG", isBigFive: false, isHost: false },
    { name: "Norway", code: "NO", flag: "🇳🇴", broadcaster: "NRK", isBigFive: false, isHost: false },
    { name: "Poland", code: "PL", flag: "🇵🇱", broadcaster: "TVP", isBigFive: false, isHost: false },
    { name: "Portugal", code: "PT", flag: "🇵🇹", broadcaster: "RTP", isBigFive: false, isHost: false },
    { name: "Romania", code: "RO", flag: "🇷🇴", broadcaster: "TVR", isBigFive: false, isHost: false },
    { name: "San Marino", code: "SM", flag: "🇸🇲", broadcaster: "SMRTV", isBigFive: false, isHost: false },
    { name: "Serbia", code: "RS", flag: "🇷🇸", broadcaster: "RTS", isBigFive: false, isHost: false },
    { name: "Sweden", code: "SE", flag: "🇸🇪", broadcaster: "SVT", isBigFive: false, isHost: false },
    { name: "Switzerland", code: "CH", flag: "🇨🇭", broadcaster: "SRG SSR", isBigFive: false, isHost: false },
    { name: "Ukraine", code: "UA", flag: "🇺🇦", broadcaster: "UA:PBC", isBigFive: false, isHost: false },
    { name: "United Kingdom", code: "GB", flag: "🇬🇧", broadcaster: "BBC", isBigFive: true, isHost: false }
];

// Default to 2026 countries
let countries = [...countries2026];
let currentYear = 2026;
